import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { radius } from '../../../theme/radius';
import { spacing } from '../../../theme/spacing';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
    gap: spacing.md,
  },
  loadingText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    color: '#46607A',
    textAlign: 'center',
  },
  scroll: {
    flexGrow: 1,
    paddingTop: 18,
    paddingHorizontal: spacing.xl,
    paddingBottom: 32,
    gap: spacing.lg,
  },
  header: {
    gap: spacing.md,
    paddingTop: 8,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9E5F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressed: {
    opacity: 0.82,
  },
  eyebrow: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#1D4ED8',
  },
  title: {
    fontFamily: 'Inter_700Bold',
    fontSize: 30,
    color: '#0F172A',
    letterSpacing: -0.8,
  },
  subtitle: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#5B7186',
    maxWidth: '94%',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    padding: spacing.xl,
    gap: spacing.md,
    overflow: 'hidden',
  },
  summaryGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    top: -60,
    right: -70,
    backgroundColor: 'transparent',
  },
  summaryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  summaryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.full,
  },
  summaryBadgeText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
  },
  summaryMeta: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#64748B',
  },
  summaryTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 22,
    color: '#0F172A',
  },
  summaryText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#475569',
  },
  summaryStats: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  summaryStat: {
    flex: 1,
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#E3EDF5',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
    gap: 5,
  },
  summaryStatValue: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: '#0F172A',
  },
  summaryStatLabel: {
    fontFamily: 'Inter_400Regular',
    fontSize: 11,
    lineHeight: 16,
    color: '#64748B',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    padding: spacing.lg,
    gap: spacing.md,
  },
  cardHeader: {
    gap: 6,
  },
  cardTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  cardDescription: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#64748B',
  },
  infoList: {
    borderRadius: 20,
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#E3EDF5',
    overflow: 'hidden',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
  },
  infoRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#E3EDF5',
  },
  infoIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#E8F1FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCopy: {
    flex: 1,
    gap: 2,
  },
  infoLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#3B82F6',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  infoValue: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: '#0F172A',
  },
  buttonSecondary: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
  },
  buttonSecondaryText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    color: '#F8FAFC',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  toggleList: {
    gap: 12,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: 4,
  },
  toggleIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#E8F1FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleCopy: {
    flex: 1,
    gap: 3,
  },
  toggleTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: '#0F172A',
  },
  toggleDescription: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
  },
  actionList: {
    gap: 10,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#E3EDF5',
    borderRadius: 18,
  },
  actionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIconDefault: {
    backgroundColor: '#E8F1FB',
  },
  actionIconDanger: {
    backgroundColor: '#FEF2F2',
  },
  actionCopy: {
    flex: 1,
    gap: 2,
  },
  actionTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: '#0F172A',
  },
  actionTitleDanger: {
    color: '#991B1B',
  },
  actionText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
  },
  footerCard: {
    backgroundColor: '#FFF5F5',
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#FECACA',
    padding: spacing.lg,
    gap: spacing.md,
  },
  footerTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    color: '#991B1B',
  },
  footerText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#B91C1C',
  },
  signOutButton: {
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: '#7F1D1D',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
  },
  signOutText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    color: colors.white,
  },
});
