import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { radius } from '../../../theme/radius';
import { spacing } from '../../../theme/spacing';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F4F8FC' },
  keyboardArea: { flex: 1 },
  scroll: {
    flexGrow: 1,
    paddingBottom: 36,
  },
  heroSection: {
    paddingTop: 18,
    paddingHorizontal: spacing.xl,
    paddingBottom: 26,
    gap: spacing.lg,
  },
  bodySheet: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    paddingTop: 12,
    paddingBottom: 36,
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 16,
  },
  bodyContent: {
    paddingHorizontal: spacing.xl,
    gap: spacing.lg,
  },
  handle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#93C5FD',
    alignSelf: 'center',
    marginBottom: 24,
  },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.65 },
  header: { gap: spacing.md },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.85)',
  },
  eyebrow: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#2563EB',
  },
  headerTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 30,
    color: '#0F172A',
    letterSpacing: -0.8,
  },
  headerSubtitle: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#64748B',
    maxWidth: '94%',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    padding: spacing.xl,
    gap: spacing.md,
  },
  avatarCard: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
  },
  avatarShell: {
    width: 116,
    height: 116,
    borderRadius: 58,
    padding: 4,
    backgroundColor: 'rgba(255,255,255,0.52)',
    marginBottom: 14,
  },
  avatarImage: { width: '100%', height: '100%', borderRadius: 54 },
  avatarFallback: {
    width: '100%',
    height: '100%',
    borderRadius: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontFamily: 'Inter_700Bold', fontSize: 42, color: '#FFFFFF' },
  cameraBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#DBEAFE',
  },
  heroNamePreview: {
    fontFamily: 'Inter_700Bold',
    fontSize: 24,
    color: '#0F172A',
    textAlign: 'center',
  },
  heroEmail: {
    marginTop: 4,
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    color: '#334155',
    textAlign: 'center',
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: 16,
  },
  secondaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.75)',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  secondaryChipText: { fontFamily: 'Inter_600SemiBold', fontSize: 13, color: '#1D4ED8' },
  ghostChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.75)',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  ghostChipText: { fontFamily: 'Inter_600SemiBold', fontSize: 13, color: '#DC2626' },
  sectionTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  sectionText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#64748B',
  },
  field: { gap: 8 },
  fieldLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#334155',
  },
  inputShell: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: '#F8FBFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: spacing.md,
  },
  inputShellMulti: {
    alignItems: 'flex-start',
    minHeight: 132,
    paddingVertical: 14,
  },
  input: {
    flex: 1,
    minHeight: 54,
    fontFamily: 'Inter_500Medium',
    fontSize: 15,
    color: '#0F172A',
  },
  inputMulti: {
    flex: 1,
    minHeight: 100,
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    lineHeight: 22,
    color: '#0F172A',
    paddingTop: 2,
  },
  helperText: { fontFamily: 'Inter_400Regular', fontSize: 12, color: '#64748B' },
  infoCard: {
    backgroundColor: '#F8FBFF',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  infoRow: { paddingHorizontal: spacing.md, paddingVertical: 14, gap: 4 },
  infoRowBorder: { borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  infoLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#64748B',
  },
  infoValue: { fontFamily: 'Inter_600SemiBold', fontSize: 14, color: '#0F172A' },
  errorText: { fontFamily: 'Inter_500Medium', fontSize: 13, color: '#DC2626' },
  saveButtonWrap: { borderRadius: 18, overflow: 'hidden' },
  saveButton: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.primary,
  },
  saveButtonText: { fontFamily: 'Inter_700Bold', fontSize: 15, color: '#FFFFFF' },
});
