import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { radius } from '../../../theme/radius';
import { spacing } from '../../../theme/spacing';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  scroll: {
    flexGrow: 1,
    paddingTop: 18,
    paddingHorizontal: spacing.xl,
    paddingBottom: 32,
    gap: spacing.lg,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
    gap: spacing.md,
  },
  loadingText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    color: '#46607A',
    textAlign: 'center',
  },
  header: {
    gap: spacing.md,
    paddingTop: 8,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9E5F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressed: {
    opacity: 0.82,
  },
  eyebrow: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#1D4ED8',
  },
  title: {
    fontFamily: 'Inter_700Bold',
    fontSize: 30,
    color: '#0F172A',
    letterSpacing: -0.8,
  },
  subtitle: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#5B7186',
    maxWidth: '94%',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    padding: spacing.xl,
    gap: spacing.md,
    overflow: 'hidden',
  },
  summaryGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    top: -60,
    right: -70,
    backgroundColor: 'transparent',
  },
  summaryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  summaryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.full,
  },
  summaryBadgeText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
  },
  summaryMeta: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#64748B',
  },
  summaryTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 22,
    color: '#0F172A',
  },
  summaryText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#475569',
  },
  summaryStats: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  summaryStat: {
    flex: 1,
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#E3EDF5',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
    gap: 5,
  },
  summaryStatValue: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: '#0F172A',
  },
  summaryStatLabel: {
    fontFamily: 'Inter_400Regular',
    fontSize: 11,
    lineHeight: 16,
    color: '#64748B',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    padding: spacing.lg,
    gap: spacing.md,
  },
  cardHeader: {
    gap: 6,
  },
  cardTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  cardDescription: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#64748B',
  },
  buttonPrimary: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
  },
  buttonPrimaryText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    color: '#F8FAFC',
  },
  buttonSecondary: {
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
  },
  buttonSecondaryText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    color: '#1D4ED8',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  activityList: {
    gap: 12,
  },
  activityCard: {
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#E3EDF5',
    borderRadius: 22,
    padding: spacing.md,
    gap: 12,
  },
  activityTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  activityIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityCopy: {
    flex: 1,
    gap: 4,
  },
  activityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  activityTitle: {
    flex: 1,
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
    lineHeight: 21,
    color: '#0F172A',
  },
  unreadDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#DB2777',
  },
  activityBody: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#5B7186',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  chipText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#475569',
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  footerMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  footerText: {
    flex: 1,
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#64748B',
  },
  emptyWrap: {
    gap: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
  },
  emptyIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 20,
    backgroundColor: '#E8F1FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    color: '#0F172A',
    textAlign: 'center',
  },
  emptyText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#64748B',
    textAlign: 'center',
  },
  guestCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#D9E5F0',
    padding: spacing.xl,
    gap: spacing.md,
    alignItems: 'flex-start',
  },
  guestIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: '#E8F1FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 22,
    color: '#0F172A',
  },
  guestText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#5B7186',
  },
  fullWidthButton: {
    width: '100%',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusPill: {
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
  },
  statusText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#64748B',
  },
  subtleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  subtleLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#64748B',
  },
  subtleValue: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    color: colors.primary,
  },
});
