import { StyleSheet } from 'react-native';

import { radius } from '../../../theme/radius';
import { spacing } from '../../../theme/spacing';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#020617' },
  scroll: {
    paddingTop: 52,
    paddingHorizontal: spacing.xl,
    paddingBottom: 36,
    gap: spacing.lg,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center' },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(15,23,42,0.42)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#F8FAFC',
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    letterSpacing: -0.3,
  },
  headerGhost: { width: 40 },
  heroBlock: {
    gap: spacing.md,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.full,
    backgroundColor: 'rgba(96,165,250,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(147,197,253,0.18)',
  },
  heroBadgeText: {
    color: '#BFDBFE',
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
  },
  heroTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 34,
    lineHeight: 40,
    color: '#FFFFFF',
    letterSpacing: -0.8,
  },
  heroSubtitle: {
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    lineHeight: 23,
    color: '#E2E8F0',
  },
  tabRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  tabBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(191,219,254,0.22)',
    backgroundColor: 'rgba(15,23,42,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  tabBtnActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
  },
  tabText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    color: '#CBD5E1',
  },
  tabTextActive: {
    color: '#1E3A8A',
  },
  quickRead: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(191,219,254,0.2)',
    padding: spacing.lg,
    gap: spacing.md,
  },
  quickReadLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 13,
    color: '#DBEAFE',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  highlightRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  highlightIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: 'rgba(239,246,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  highlightCopy: { flex: 1 },
  highlightTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  highlightText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#E2E8F0',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.lg,
    gap: spacing.lg,
  },
  sheetTop: {
    gap: 6,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  sheetTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 22,
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  sheetIntro: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#64748B',
  },
  sectionsList: {
    gap: spacing.sm,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: spacing.md,
  },
  sectionMarkerWrap: {
    alignItems: 'center',
    width: 28,
  },
  sectionMarker: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionMarkerText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    color: '#1D4ED8',
  },
  sectionLine: {
    flex: 1,
    width: 1,
    backgroundColor: '#DBEAFE',
    marginTop: 8,
    marginBottom: -8,
  },
  sectionContent: {
    flex: 1,
    paddingBottom: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  sectionTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  sectionBody: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#475569',
    marginTop: 6,
  },
  contactStrip: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: '#F8FBFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    padding: spacing.lg,
  },
  contactIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactCopy: {
    flex: 1,
  },
  contactTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
    color: '#1E3A8A',
  },
  contactText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#334155',
    marginTop: 4,
  },
  pressed: { opacity: 0.8 },
});
